name: pimouse ROS CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests inside ROS melodic container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/root/pimouse_2025 \
            ros:melodic-ros-base-bionic \
            bash -c "
              apt update && \
              apt install -y sudo python3-pip build-essential \
                             ros-melodic-catkin ros-melodic-rostest \
                             python3-rosdep git xvfb && \
              rosdep init || true && \
              rosdep update && \
              source /opt/ros/melodic/setup.bash && \
              mkdir -p /root/catkin_ws/src && \
              ln -s /root/pimouse_2025 /root/catkin_ws/src/pimouse_2025 && \
              cd /root/catkin_ws && \
              rosdep install --from-paths src --ignore-src -r -y && \
              catkin_make && \
              source devel/setup.bash && \
              xvfb-run -a rostest pimouse_2025 test.launch
            "
